### ISSUE TITLE
Need control over line length poor readability

### ISSUE THREAD

**Issue by MacBox7** [gawdsnitkkr/sell-my-services-backend#11]
Default for node is 80

**Comment by varunon9** [comment]
while 80 is standard, sometimes it's hard to maintain it when using nested promises. @AnshulMalik  any thought?

**Comment by MacBox7** [comment]
It's never hard to maintain it. If you are having too much nesting, high complexity i.e bad logic. Improve code rather than ignore it.

**Comment by varunon9** [comment]
point taken, thanks :D :D

**Comment by AnshulMalik** [comment]
One simple way: Use 2 space for tabs instead of 4 ::P
