### ISSUE TITLE
Integrate linter

### ISSUE THREAD

**Issue by MacBox7** [gawdsnitkkr/sell-my-services-backend#12]
To ensure good code rather than specifying things on README integrate `eslint` or `jslint`.
Enable CircleCI or Travis also for the repo so that every commit and push are verified.

**Comment by varunon9** [comment]
yep. future plan. Thanks :)

**Comment by MacBox7** [comment]
Won't take more than few minutes. Would be hard to fix stuff in later stage. It need not be too complex for current stage.

**Comment by varunon9** [comment]
sounds cool :+1:  point taken

**Comment by AnshulMalik** [comment]
Would like to set the linter up? @MacBox7

**Comment by MacBox7** [comment]
Not atm :smile:
