### ISSUE TITLE
Enable logging

### ISSUE THREAD

**Issue by MacBox7** [gawdsnitkkr/sell-my-services-backend#13]
`console.log` is a very bad way to do logging. Use a customizable logger and log at appropriate levels.

**Comment by varunon9** [comment]
Agree.
Though console.log/console.error was solving purpose when used with pm2, it's not scalable.
A logger which will create log files date-wise would be better. Any suggestion?

**Comment by MacBox7** [comment]
I used winston for my [project](https://github.com/MacBox7/torque/blob/master/local-blockchain-manager/logger.js). Good enough and easily customizable you can redirect the output to file with some modifications rather than stdout, stderr.

**Comment by varunon9** [comment]
Thanks. We'll implement it. Btw you can also raise a PR :smile:

**Comment by MacBox7** [comment]
Busy atm. Would contribute when free.

**Comment by varunon9** [comment]
sure :)
