### ISSUE TITLE
Save request-log into files instead of database

### ISSUE THREAD

**Issue by AnshulMalik** [gawdsnitkkr/sell-my-services-backend#2]
There are many points to consider:
- Writing to files in this case is much faster than writing in database
- It will fill the database really fast
- Make the database slower over time
- Databases are not cheap

We can store logs into file with max size of file, and have their backup somewhere. That way we save both on space and time.

**Comment by varunon9** [comment]
Agree.
We can decide a proper format and put request-log in file.
Reason to put into database was to access it to have study over it but that can also be achieved by parsing logs files(so proper format is necessary).
