### ISSUE TITLE
winston logger sometimes not printing `err` object 

### ISSUE THREAD

**Issue by varunon9** [gawdsnitkkr/sell-my-services-backend#22]
`logger.error('message', err); // err is error object`
Sometimes logger is printing only message and not err object

How to reproduce-
in file `routes/search.js` edit line no 14 from `res.status(statusCode.SC_OK);` to `res.status(statusCode.OK);`
invalid status code error will be thrown but it will be not logged on line no 22 `logger.error('Error /search/sellers', err);`

**Comment by AnshulMalik** [comment]
Its not printing **every time** for me.

**Comment by varunon9** [comment]
two options-
1. move to bunyan
2. can try printing err using es6 template e.g. logger.error(`Message ${err}`);

**Comment by varunon9** [comment]
switched to bunyan now
