### ISSUE TITLE
Extract status code logic from services

### ISSUE THREAD

**Issue by AnshulMalik** [gawdsnitkkr/sell-my-services-backend#24]
Services should not be concerned with http stuff. 

So it'd be better if the request handlers take care of handling response. And services handle the business logic.

**Comment by varunon9** [comment]
Lets add another layer `controller` between routes and service.
API normal flow would be-
1. request hit routes
2. routes will call corresponding controller excepting a promise (response data + status code)
3. controller will validate about missing params or permission or if data exists in db etc. It'll call then service. It'll generate response code accordingly. 
4. Service will assume that all validations have been taken care of and it'll be simple and pure db interaction.
